language: cpp
compiler: gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install gcc-multilib libnotify-dev libv8-dev libboost-dev libboost-date-time-dev libboost-filesystem-dev libboost-thread-dev libboost-system-dev libboost-test-dev
  - wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/libwxgtk2.9-dev_2.9.3-1_amd64.deb"
  - wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/wx2.9-headers_2.9.3-1_amd64.deb"
  - wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/libwxgtk2.9-0_2.9.3-1_amd64.deb"
  - wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/libwxbase2.9-dev_2.9.3-1_amd64.deb"
  - wget "http://ppa.launchpad.net/fransschreuder1/usbpicprog-stable/ubuntu/pool/main/w/wxwidgets2.9/libwxbase2.9-0_2.9.3-1_amd64.deb"
  - sudo dpkg --install libwxbase2.9-0_2.9.3-1_amd64.deb
  - sudo dpkg --install libwxgtk2.9-0_2.9.3-1_amd64.deb
  - sudo dpkg --install wx2.9-headers_2.9.3-1_amd64.deb
  - sudo dpkg --install libwxbase2.9-dev_2.9.3-1_amd64.deb
  - sudo dpkg --install libwxgtk2.9-dev_2.9.3-1_amd64.deb
before_script:
  - mkdir build
  - cd build
script:
  - cmake .. -DBUILD_CEF=off -DWITH_ARES=off -DDEBUG=on
  - make -j4
  - ctest --output-on-failure .
notifications:
  irc:
    channels:
      - "irc.freenode.org#desura"
    template:
      - "%{repository} (%{commit}) by %{author} : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Latest commit: %{compare_url}"
    on_success: change
    on_failure: change
